services:
  - type: web
    name: taskflow
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && python manage.py migrate"
    startCommand: "gunicorn taskmanager.wsgi --log-file -"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: taskflow-db
          property: connectionString

databases:
  - name: taskflow-db
    plan: free
